// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	FirstName string `json:"firstName" `
	LastName  string `json:"lastName"`
	Age       int    `json:"Age"`
}

type DeleteUserInput struct {
	ID string `json:"id"`
}

type User struct {
	ID        string `json:"id" redis:"id"`
	FirstName string `json:"firstName" redis:"firstname"`
	LastName  string `json:"lastName" redis:"lastname"`
	Age       int    `json:"Age" redis:"age"`
}
